variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - Build
  - Test
  - Deploy

qt_6.8.0:
  stage: Build
  image:
    name: "carlonluca/qt-dev:6.8.0"
    entrypoint: [""]
  script:
    - mkdir build
    - mkdir deploy
    - cd build
    - cmake -S .. -G Ninja -DCMAKE_BUILD_TYPE=Release
    - ninja
  artifacts:
    paths:
      - "build/"
      - "deploy/"

unit_test:
  stage: Test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 20
    - echo "Code coverage is 90%"

cppcheck:
  stage: Test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

clang_tidy:
  stage: Test
  script:
    - echo "Clang-tidy... This will take about 10 seconds."
    - sleep 10
    - echo "No erros are found."    

deploy_linux_x86_deb:
  stage: Deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Creating *.deb file"
    - echo "Application successfully deployed."
